# Generated by Django 3.0.7 on 2020-10-29 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probNo', models.IntegerField()),
                ('psname', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=5000)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamNo', models.IntegerField()),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Taken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psNo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='problemstatementNum', to='Select.ProblemStatement')),
                ('tNo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teamNum', to='Select.ProblemStatement')),
            ],
        ),
    ]
